// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.4.0
// source: discordbot.proto

package pgk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Discordbot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	Cause string `protobuf:"bytes,15,opt,name=cause,proto3" json:"cause,omitempty"`
	User  string `protobuf:"bytes,26,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *Discordbot) Reset() {
	*x = Discordbot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discordbot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Discordbot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discordbot) ProtoMessage() {}

func (x *Discordbot) ProtoReflect() protoreflect.Message {
	mi := &file_discordbot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discordbot.ProtoReflect.Descriptor instead.
func (*Discordbot) Descriptor() ([]byte, []int) {
	return file_discordbot_proto_rawDescGZIP(), []int{0}
}

func (x *Discordbot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Discordbot) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *Discordbot) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

var File_discordbot_proto protoreflect.FileDescriptor

var file_discordbot_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x0a, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x72, 0x64, 0x62, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x61, 0x75, 0x73, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x75, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x1a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x75, 0x63, 0x6f, 0x6f, 0x69, 0x6e, 0x67, 0x2f, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x72, 0x64, 0x62, 0x6f, 0x74, 0x2d, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_discordbot_proto_rawDescOnce sync.Once
	file_discordbot_proto_rawDescData = file_discordbot_proto_rawDesc
)

func file_discordbot_proto_rawDescGZIP() []byte {
	file_discordbot_proto_rawDescOnce.Do(func() {
		file_discordbot_proto_rawDescData = protoimpl.X.CompressGZIP(file_discordbot_proto_rawDescData)
	})
	return file_discordbot_proto_rawDescData
}

var file_discordbot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_discordbot_proto_goTypes = []interface{}{
	(*Discordbot)(nil), // 0: proto.Discordbot
}
var file_discordbot_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_discordbot_proto_init() }
func file_discordbot_proto_init() {
	if File_discordbot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_discordbot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Discordbot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_discordbot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_discordbot_proto_goTypes,
		DependencyIndexes: file_discordbot_proto_depIdxs,
		MessageInfos:      file_discordbot_proto_msgTypes,
	}.Build()
	File_discordbot_proto = out.File
	file_discordbot_proto_rawDesc = nil
	file_discordbot_proto_goTypes = nil
	file_discordbot_proto_depIdxs = nil
}
